apk add --no-cache python3=3.5.6-r0 doesn't work
~~~sh
$ make -f docker.mk build
docker build -t tamakiii-sandbox/hello-apk-specific-version .
Sending build context to Docker daemon  69.12kB
Step 1/2 : FROM alpine:3.11.3
 ---> e7d92cdc71fe
Step 2/2 : RUN apk add --no-cache python3=3.5.6-r0
 ---> Running in ccf6da63264d
fetch http://dl-cdn.alpinelinux.org/alpine/v3.11/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.11/community/x86_64/APKINDEX.tar.gz
ERROR: unsatisfiable constraints:
  python3-3.8.1-r0:
    breaks: world[python3=3.5.6-r0]
The command '/bin/sh -c apk add --no-cache python3=3.5.6-r0' returned a non-zero code: 1
make: *** [build] Error 1
~~~